### ISSUE TITLE
New version available

### ISSUE THREAD

**Issue by rzulian** [rzulian/lutron_custom_component#8]
Hey,
I've created a new version here [homeassistant/components/lutron](https://github.com/rzulian/core/tree/lutron-aoilip/homeassistant/components/lutron)

New addition:

- **New communication lib**: This is version is not using the deprecated telnetlib, and it's fully asynchronous.
- **Pylutron**: I've removed the dependency to Pylutron, which was a source of problem because it was conflicting with the official release.
- **Variables** I've added the ability to manage variables. You still need to add the id integration of the variables using the configuration.The variables are select entities that you can read and write. Currently the values are hardcoded to 0-5.
- **Motors**: motors are now managed using travel time. You can set the travel time for each motor in the configuration.
- **RadioRA**: I've added the parameter to allow a "compatability mode" with the current official integration. Basically button names are set from engraving and the leds are created as switches and not as lights.

@ronluna @txwindsurfer if you have time and want to test it, let me know your feedback

**Comment by ronluna** [comment]
Will do!.
Wondering if the ability for adding multiple processor can be added ?

**Comment by rzulian** [comment]
@ronluna I cannot test it, but maybe you can try to modify the manifest.json and set "single_config_entry": false

**Comment by txwindsurfer** [comment]
Wow!  Fabulous!  Thanks!

I created a test HA Core from scratch on an extra RPI 3 then downloaded the zip of this branch and copied all your files in the lutron directory to custom_components/lutron using Samba.  Rebooted HA then added the Lutron integration from the integration page with my ip.  And, everything just came up.  It just worked!  Lights, Keypad LED switches, Keypad Scenes and Occupancy.  I don't have any occupancy devices but now I sure wish I had.

The new interface creation logic in HA automatically organized everything into the rooms so the HA interface was essentially built automatically. All I did was add names and areas to the keypad devices.  

BTW, I have a Homeworks QS system. 

What is the future?  Should I put your component into production?

**Comment by rzulian** [comment]
@txwindsurfer thank you for taking time to test it.
The integration has led switches or lights? Did you check the radiora_mode?
Regarding the future. I’m using it in production and it works just fine, probably better and faster than the previous version. 
I’ve submited a PR for this to become the new integration, but this process will require some time. If for any reason it won’t be possible, i will publish it to hacs

**Comment by txwindsurfer** [comment]
@rzulian I don't believe your integration is connecting to my Homeworks QS system and instead the standard Lutron component appears to be the one connecting.  I am not sure how to determine except that the supervisor logs are not indicating a custom component is being used.  The custom_component/lutron file structure is correct but your custom component isn't loading.  Do I have to actually put your files into homeassistant/components directory instead of using the custom component approach?

When I load the Lutron component from the integration page I put in my ip address along with the standard lutron id and password.  All of the components are found but I get both LED switches AND Light entities and all of the scenes.  QS doesn't have a radiora_mode but I do have a Lutron Connect device that the Lutron RadioRa app used to control QS.  I have not been successful connecting to that device and can only connect using the lutron telnet interface.  Thanks for any thoughs on implementation.

**Comment by rzulian** [comment]
@txwindsurfer you can use the integration in the original folder or as a custom component. In this case you should see  "Custom integration that replaces a core component" in the UI

<img width="943" height="129" alt="Image" src="https://github.com/user-attachments/assets/a50f960f-2ffc-4cdd-9e3e-2635aecd2abe" />

BTW, you won't see "Lutron by Zuli" in the name, as if you copied from core to custom_component, the name is "Lutron"

Maybe `radiora_mode` is misleading, but what it means is that the integration works like the current official integration: the button name is from engraving and led are created as switch entities.

**Comment by txwindsurfer** [comment]
@rzulian Thanks for this clarification.  However, selecting Lutron ends up installing the current component not your component.  I have HACS running and the lutron directory is in the same custom_component directory as HACS and contains all your files.  I wonder if the recent grouping of integrations in the UI is an issue.  For instance Lutron in the UI contains 3 integrations.  Selecting Lutron installs the current integration.

<img width="521" height="459" alt="Image" src="https://github.com/user-attachments/assets/9866296e-b617-4437-8736-57d0014ab401" />

My custom_components director showing manifest.json:
<img width="1191" height="359" alt="Image" src="https://github.com/user-attachments/assets/6db68224-2670-49e3-8715-8afa9beddc51" />

**Comment by rzulian** [comment]
@txwindsurfer try to change the name to something else. You should see the integration under Lutron then

**Comment by txwindsurfer** [comment]
@rzulian Found the problem as the home-assistant.logs were giving this error:
`2025-07-23 10:02:33.808 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'lutron' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

So, I added version 1.0.0 (don't know how you want to version this) and your component is now connecting to Homeworks QS. BTW, I was forced to enter something for Variable field or it told me "Not all required fields are filled in"
{
  "domain": "lutron",
  "name": "Lutron",
  "version": "1.0.0"
  "codeowners": ["cdheiser", "wilburCForce", "rzulian"],
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/lutron",
  "iot_class": "local_polling",
  "requirements": ["defusedxml==0.7.1"],
  "single_config_entry": true
}

**Comment by rzulian** [comment]
Thanks, I didn't noticed that the version was missing :(
I've fixed the variable IDs ads optional

**Comment by txwindsurfer** [comment]
@rzulian My test system with your new integration implemented in radiora_mode is working great and appears to be much faster.  In order for me to try it in production, the naming scheme for LEDs needs to be the same as Scenes. The LED names in this integration are being set as Keypad LED 1, Keypad LED 2 ... for every keypad.  The current radiora Lutron component matches the LED and Scene name (e.g. Scene name = Keypad Guests and corresponding LED switch is Keypad Guests).  The same naming scheme for both Scenes and LEDs helps with automations and scipts since LEDs are the way to tell whether a Scene is on or off.

I have 1 error at startup which doesn't seem to impact anything.  Unfortunately, the startup logs don't provide any additional information:

`This error originated from a custom integration.

Logger: custom_components.lutron.aiolip
Source: custom_components/lutron/aiolip/__init__.py:250
integration: Lutron
First occurred: 11:24:38 AM (1 occurrence)
Last logged: 11:24:38 AM

Protocol Error: ~ERROR,2`

There are a couple of warnings on startup that depend on how the lutron.db is configured and can probably be ignored. 

`This error originated from a custom integration.

Logger: custom_components.lutron.lutron_db
Source: custom_components/lutron/lutron_db.py:95
integration: Lutron
First occurred: 11:24:35 AM (3 occurrences)
Last logged: 11:24:35 AM

Occupancy Group not found for Area: Outside; ID: 0
Occupancy Group not found for Area: 2nd Floor; ID: 0
Occupancy Group not found for Area: 1st Floor; ID: 0`

And, I use the old RS485 controller for some lights which work but produces these warnings:

`This error originated from a custom integration.

Logger: custom_components.lutron.lutron_db
Source: custom_components/lutron/lutron_db.py:148
integration: Lutron
First occurred: 11:24:35 AM (19 occurrences)
Last logged: 11:24:35 AM

Unknown H48_DIMMER Device type`

Thanks for making this new integration available and please let me know how I can test and help.

**Comment by rzulian** [comment]
@txwindsurfer you can download and test the latest version. It should have full compatibility in radiora_mode, so also LEDs and scenes.

```Occupancy Group not found for Area: Outside; ID: 0
Occupancy Group not found for Area: 2nd Floor; ID: 0
Occupancy Group not found for Area: 1st Floor; ID: 0
```
It's only a warning, I should remove it

H48_DIMMER is not supported. You can try to modify the lis of available devices in `lutron_db.py:131`. What kind of device is it?

You are also getting a `Protocol Error: ~ERROR,2`. Can you try to enable debug, and try to understand which command is generating this error?

If you want you can send me the xmldb so I can test the parsing.

**Comment by txwindsurfer** [comment]
@rzulian I copied the new files to the custom_component directory.  BTW, version number is still missing from manifest.json and you have to add it to load.

Deleted the integration and re-added it with Refresh Data and Radiora mode checked.  My LED names are still Keypad LED Button 1 etc.  I should note that the version of Homeworks I have does not support naming/engraving an LED component.  In the lutron_data.xml file, LEDs have component and component values but no Engraving

Button: `<Component ComponentNumber="24" ComponentType="BUTTON">
<Button Name="Button 24" UUID="1591" Engraving="LivingRoom" ButtonType="AdvancedToggle" PrimaryActionType="3" SceneSaver="false" CycleDim="false" AllowDoubleTap="true" StopIfMoving="false" ProgrammingModelID="1592" LedLogic="1" ReverseLedLogic="false">`

LED: `<Component ComponentNumber="81" ComponentType="LED">
<LED UUID="2113" isReverseLogic="false" ProgrammingModelID="2120"/>
</Component>`

I suppose the current integration names the LEDs by matching ComponentNumbers then using the Engraving value for Button {x} to name LED {x}.

The H48_DIMMER is a serial controller for light dimmer switches and can be ignored because the integration picks up the dimmer switches as Output in an Area.  It does not need any mapping to Home Assistant.  I can just ignore this warning.

I will enable debug and see if I can find more information on Protocol Error IF it happens again.  Seems to be resolved.

Here is a link to my xmldb if that can help.  `https://1drv.ms/u/c/802fc5aaff907c53/EQRPezVSjBhJk2I_5eKSdjEBz8DiLZfiEC73j1sHoxtOyw?e=MPttuj`

**Comment by rzulian** [comment]
@txwindsurfer : thank you for sharing your xmldb and thank you for the bug in the led naming.
You can download the new version.

Please make sure that you are reloading from a clean install. Usually deleting the integration is not enough. To make sure that I'm not using old entity_ids I manually delete them also from the `deleted_devices` in `.storage\core.device_registry` and from `deleted_entites` in `.storage\core.entity_registry`, and then I restart HA.

Regarding the naming. Leds don't have a name or engraving. They get the same name as the corresponding button during the parsing.
For buttons radiora_mode uses engraving if available, if not the name will be Unknown button x
For keypads radiora_mode uses the name. The problem is that in HomeworksQS the name is CSD 001, so they should use the group_name, which they store in location, but they don't.

The result is that in the current "official" integration you should get (referring to the first button and led in the keypad in the livingroom:
Device => name: CSD 001, area: LivingRoom
Button => name: DownLights => entity_id : CSD_001_downlights
LED => name: Downlights=> entity_id: CSD_001_downlights

But every keypad will have the same name!

**Comment by txwindsurfer** [comment]
@rzulian The Protocol Error has not recurred with the new version.  

Yes, I see now that you have to delete all the old deleted references to devices and entities in order for new names to be created.  I deleted as you instructed, rebooted and checked both core.entity.registry and core.device.registry files.  "lutron" was not found in either one.  Reinstalled the custom component with Refresh and use_radiora_mode checked.  For the keypad in the livingroom with Scene Downlights and LED 1, I have the following:
  
Device => name: CSD 001, area: Living Room:

`{"area_id":"living_room","config_entries":["01K1GW6BQZAVGXVZ98MZMTGZCP"],"config_entries_subentries":{"01K1GW6BQZAVGXVZ98MZMTGZCP":[null]},"configuration_url":null,"connections":[],"created_at":"2025-07-31T18:34:17.396124+00:00","disabled_by":null,"entry_type":null,"hw_version":null,"id":"280f5030f81a667c49ac2efaa5a64065","identifiers":[["lutron","44"]],"labels":[],"manufacturer":"Lutron","model":null,"model_id":null,"modified_at":"2025-07-31T18:34:17.396421+00:00","name_by_user":null,"name":"CSD 001","primary_config_entry":"01K1GW6BQZAVGXVZ98MZMTGZCP","serial_number":null,"sw_version":null,"via_device_id":"e61ad64d480b5f51290cb689fe27534c"}`

Scene (not button) => name: Downlights => entity_id: scene.csd_001_downlights_4:

`{"aliases":[],"area_id":null,"categories":{},"capabilities":{"event_types":["press","release","hold","hold_release","double_tap"]},"config_entry_id":"01K1GW6BQZAVGXVZ98MZMTGZCP","config_subentry_id":null,"created_at":"2025-07-31T18:34:17.401170+00:00","device_class":null,"device_id":"280f5030f81a667c49ac2efaa5a64065","disabled_by":null,"entity_category":null,"entity_id":"event.csd_001_downlights_4","hidden_by":null,"icon":null,"id":"8c9e0ff2d88844a0744b0895efbfd8b8","has_entity_name":true,"labels":[],"modified_at":"2025-07-31T18:34:17.413235+00:00","name":null,"options":{"conversation":{"should_expose":false}},"original_device_class":null,"original_icon":null,"original_name":"Downlights","platform":"lutron","suggested_object_id":null,"supported_features":0,"translation_key":"button","unique_id":"7c3f6b4d75f4f84eb4ad7556f499dff0_1547","previous_unique_id":null,"unit_of_measurement":null},
`

LED => name: LED 1 => entity_id: switch.csd_001_led_1_4:

`{"aliases":[],"area_id":null,"categories":{},"capabilities":null,"config_entry_id":"01K1GW6BQZAVGXVZ98MZMTGZCP","config_subentry_id":null,"created_at":"2025-07-31T18:34:19.279025+00:00","device_class":null,"device_id":"06000db82c6281b9a9e5c850155c1d2c","disabled_by":null,"entity_category":null,"entity_id":"switch.csd_001_led_4","hidden_by":null,"icon":null,"id":"4bc2b0af8cb409b82d3422e34f7bc9e6","has_entity_name":true,"labels":[],"modified_at":"2025-07-31T18:34:19.283328+00:00","name":null,"options":{"conversation":{"should_expose":true}},"original_device_class":null,"original_icon":null,"original_name":"LED 4","platform":"lutron","suggested_object_id":null,"supported_features":0,"translation_key":null,"unique_id":"7c3f6b4d75f4f84eb4ad7556f499dff0_2116","previous_unique_id":null,"unit_of_measurement":null},`

I don't have buttons created with Homeworks QS but Scenes.  This is true for both your integration and the official integration.  Events are also created but I am not including those.  If this is what you were expecting from a Homework QS system then all is good.  Implementing in my production HA would keep/reuse the existing names I have set for devices, scenes, led, and events  since I'm not starting from a fresh install--I think.

**Comment by rzulian** [comment]
@txwindsurfer my bad, Lutron buttons are used as scenes or events in HA.
In your production HA, which integration are you running?

**Comment by txwindsurfer** [comment]
The RadioRA version. https://www.home-assistant.io/integrations/lutron/   Homeworks QS and RadioRA use the same command structure.  While the document states differently it is compatible with Homeworks QS.

The Lutron integration labeled Homeworks is for old Homeworks Series 4 & 8 and has a totally different command structure.

**Comment by rzulian** [comment]
I'm confused. The official integration shouldn't connect to HomeworksQS because it's waiting for GNET prompt and not for QNET

**Comment by txwindsurfer** [comment]
That was true for a long time and I had to manually change the prompt match after each update.  But a year or so back, a version was created that worked.  I think it may time out and thereby ignore the prompt not matching, but really can't remember.  But, it does work.

**Comment by rzulian** [comment]
New version available. I've added the connection status sensor, just in case. And also moved variables to the main device. Regarding variables, @ronluna : did you have time to test if they work as expected?

**Comment by txwindsurfer** [comment]
@rzulian 

(Note: copying new files from aiolip directors fixed errors from any previous edits).

Remember to add some version to manifest.json
{
  "domain": "lutron",
  "name": "Lutron",
  "version": "1.0.0",
  "codeowners": ["@cdheiser", "@wilburCForce", "@rzulian"],
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/lutron",
  "iot_class": "local_polling",
  "requirements": ["defusedxml==0.7.1"],
  "single_config_entry": true
}

**Comment by rzulian** [comment]
> Remember to add some version to manifest.json
> {
> "domain": "lutron",
> "name": "Lutron",
> "version": "1.0.0",
> "codeowners": ["[@cdheiser](https://github.com/cdheiser)", "[@wilburCforce](https://github.com/wilburCforce)", "[@rzulian](https://github.com/rzulian)"],
> "config_flow": true,
> "documentation": "https://www.home-assistant.io/integrations/lutron",
> "iot_class": "local_polling",
> "requirements": ["defusedxml==0.7.1"],
> "single_config_entry": true
> }

Well, I've tried, but I'm getting 
```Invalid integrations: 1
Found errors. Generating files canceled.
Integration lutron:
* [ERROR] [MANIFEST] Invalid manifest: extra keys not allowed @ data['version']. Got '1.0.0'
```
I will investigate it

**Comment by txwindsurfer** [comment]
I think I got this error when I forgot to put a comma at the end of the line.  Or, you are probably running this integration in a complete standalone instance rather than a custom component replacing lutron.  "Version" is a requirement for a custom components but is not allowed for an official integration.

**Comment by txwindsurfer** [comment]
@rzulian.  I am so happy that you are working on the lutron integration and I hope I am helping and not being a bother.  

_Edit:  Opps it was a typo!  Fixed and working_

In order for me to put your lutron integration into production, I created a folder in custom_components than isn't named lutron because if named lutron, it replaces the entire lutron integration domain including the Lutron Caseta integration which I also use in my production system.  I renamed the folder lutron_aiolit and changed the domain and name in manifest.json to correspond.  I also changed the one line in const.py: DOMAIN = "lutron_aiolip".  I can now see both the lutron_aoilip domain **and** official lutron doman/brand with the Caseta integration within it.  

All is working great in productions.  To match up my names I checked the boxes for refresh_data, use_area_for_device_name and use_radiora_mode.  Installed perfectly and much faster.  Thank you!

**Comment by rzulian** [comment]
@ronluna I've tried your setup and it's working. You need to have the same name in the directory, in the DOMAIN and in the manifest domain. In your message it seems you have lutron_aoilit and lutron_aiolip.

Edit: actually I think the problem is that your Core version is an old one and it's not supporting `AddConfigEntryEntitiesCallback`. Ive noticed this while creating the HACS custom component.

**Comment by txwindsurfer** [comment]
@rzulian Everything is working great in production and seems faster with Homeworks QS (radiora_mode).  I did get one nasty failure when I think HA tried to communicate with HW while HW was in a transfer or reboot state and would not respond.  This caused HA to completely freeze and I had to restart core from terminal login.  I took a screen shot of the core logs.  You may want to ignore it, but thought it might be helpful.

<img width="833" height="1335" alt="Image" src="https://github.com/user-attachments/assets/eb7242fc-f480-466c-a0a8-fc74827e0e5d" />

**Comment by rzulian** [comment]
Thank you for reporting this bug. I will try to make a nicer behavior when disconnected!

**Comment by rzulian** [comment]
@ronluna @txwindsurfer This component is now (finally) available in HACS! You need to search for Lutron LIP. If you have time please test it out. Let's move the conversation over to https://github.com/rzulian/lutron_lip!

I have also created a post here https://community.home-assistant.io/t/lutron-homework-qs-and-radiora2-integration/920503

**Comment by txwindsurfer** [comment]
@rzulian Done!  All is working with the HACS verson.  I didn't want to start a new issue, but did want let you know that I installed in production and I am extremely happy.  Thank you so much!  How do I send $$ for the case of beer?
